-- Run this after the tables SQL

-- 10 FAQs
INSERT INTO faqs (question, answer, category, sort_order, is_published) VALUES
('What is a Google Play Store review service?', 'A Google Play Store review service helps app developers improve their app ratings and review profiles by connecting them with real, active users who provide genuine feedback. Unlike fake review services, we ensure authenticity and compliance with Google Play policies.', 'General', 1, true),
('Is this service safe for my app?', 'Yes, absolutely. We use only real users with active Google accounts to leave reviews. Every review comes from a genuine device, making it indistinguishable from organic reviews. We follow Google Play guidelines to keep your app safe.', 'Safety', 2, true),
('How long does it take to see results?', 'Most clients see noticeable improvements within 3-7 days. The exact timeline depends on your current rating, the number of reviews needed, and your app category. We provide real-time progress updates throughout the process.', 'Process', 3, true),
('Will the reviews be permanent?', 'Yes. All reviews we deliver are from real users and are permanent. Unlike bot-generated reviews that get removed by Google, our reviews stay on your listing permanently because they come from genuine user activity.', 'Safety', 4, true),
('Can I choose the rating my app receives?', 'We focus on organic-style growth. While we cannot guarantee exact star ratings, we aim for genuine 4-5 star reviews by targeting users who are likely to appreciate your app. Our goal is sustainable, realistic growth.', 'General', 5, true),
('How do I get started?', 'Getting started is simple. Contact us via WhatsApp, Telegram, or our contact form. Tell us about your app, its current rating, and your goals. We will create a customized plan and get started within 24 hours.', 'Process', 6, true),
('What information do you need about my app?', 'We need your app name, package URL from Google Play Store, current rating, and your target goals. Optional details like app category, target audience, and specific concerns help us tailor our approach for better results.', 'General', 7, true),
('Do you offer refunds?', 'Yes. We offer a satisfaction guarantee. If you are not happy with the results within the first 7 days, we will work to make it right or provide a refund. Your trust and satisfaction are our top priority.', 'Support', 8, true),
('Will Google ban my account for using this service?', 'No. We use authentic user reviews that comply with Google Play policies. Our methods mimic natural user behavior, so there is no risk of account suspension. We have served 500+ apps with zero account issues.', 'Safety', 9, true),
('How do you find real users for reviews?', 'We have a network of real Android users across different countries and demographics. These are genuine people who download, use, and review apps naturally. We match your target audience with the right reviewers for authentic feedback.', 'Process', 10, true);
